export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLES = 'GET_ARTICLES';
export const GET_ARTICLES_START = 'GET_ARTICLES_START';
export const GET_ARTICLES_SUCCESS = 'GET_ARTICLES_SUCCESS';
export const GET_ARTICLES_FAIL = 'GET_ARTICLES_FAIL';

